<?php /** @var string $content */?>

<!DOCTYPE html>
<html lang="ru">
<head>
    <title>Mixail</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="/css/style.css" rel="stylesheet">
</head>
<body class="text-center">
<?= $content ?>
<a href="/">Главная</a>
<a href="/login">Вход</a>
<a href="/registration">Регистрация</a>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="/js/script.js"></script>
</body>
</html>
