<form id="login_form" class="form-signin" action="/login" method="post">
    <h1 class="h3 mb-3 font-weight-normal">Вход</h1>
    <label for="login" class="sr-only">Логин</label>
    <input name="login" type="text" id="login" class="form-control" placeholder="Логин" required>
    <label for="inputPassword" class="sr-only">Пароль</label>
    <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Пароль" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
</form>