<form id="registration_form" class="form-signin" action="/registration" method="post">
    <h1 class="h3 mb-3 font-weight-normal">Регистрация</h1>
    <label for="name" class="sr-only">Имя</label>
    <input name="name" type="text" id="name" class="form-control" placeholder="Имя" required>
    <label for="login" class="sr-only">Логин</label>
    <input name="login" type="text" id="login" class="form-control" placeholder="Логин" required>
    <label for="inputEmail" class="sr-only">Email</label>
    <input name="email" type="email" id="inputEmail" class="form-control" placeholder="Email" required>
    <label for="inputPassword" class="sr-only">Пароль</label>
    <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Пароль" required>
    <label for="confirmPassword" class="sr-only">Повторите пароль</label>
    <input name="confirmPassword" type="password" id="confirmPassword" class="form-control" placeholder="Повторите пароль" required>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Зарегистрироваться</button>
</form>